FROM node:12-alpine AS builder
RUN mkdir -p /usr/app
WORKDIR /usr/app
COPY package.json tsconfig.json ./
RUN npm install
COPY src ./src
COPY public ./public
RUN npm run build


FROM node:12-alpine AS server
WORKDIR /usr/app
COPY package* ./
RUN npm install --production
COPY --from=builder ./usr/app/public ./public
COPY --from=builder ./usr/app/build ./build
EXPOSE 4000
CMD ["npm", "start"]